name: chatapp_uc
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'

dependencies:
  agora_uikit: ^1.3.3
  audioplayers: ^4.0.1
  cached_network_image: ^3.2.3
  cached_video_player: ^2.0.4
  cloud_firestore: ^4.6.0
  country_picker: ^2.0.20
  cupertino_icons: ^1.0.2
  emoji_picker_flutter: ^1.5.4
  enough_giphy_flutter: ^0.4.0
  equatable: ^2.0.5
  firebase_auth: ^4.5.0
  firebase_auth_web: ^5.4.0
  firebase_core: ^2.11.0
  firebase_storage: ^11.1.2
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.6
  flutter_riverpod: ^2.3.6
  flutter_sound: ^9.2.13
  image_picker: ^0.8.7+4
  intl: ^0.17.0
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  story_view: ^0.14.0
  swipe_to: ^1.0.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/.
    - assets/loginpage/.
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
