// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvTPIC0cvMiXcdXgyEfuXHAz3p9-sASgE',
    appId: '1:530270654942:web:6aad7f0f6062ed8d9d0d4f',
    messagingSenderId: '530270654942',
    projectId: 'ijob-app-53532',
    authDomain: 'ijob-app-53532.firebaseapp.com',
    databaseURL: 'https://ijob-app-53532-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ijob-app-53532.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhgKsPV0E5Zj_3onbLDKPqUlURrG90S4Y',
    appId: '1:530270654942:android:d69d3d2f8249eb3a9d0d4f',
    messagingSenderId: '530270654942',
    projectId: 'ijob-app-53532',
    databaseURL: 'https://ijob-app-53532-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ijob-app-53532.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyI1LTXjrHkhe114VCUBqe6G54n5lgIE4',
    appId: '1:530270654942:ios:9746e57fa9c03a1f9d0d4f',
    messagingSenderId: '530270654942',
    projectId: 'ijob-app-53532',
    databaseURL: 'https://ijob-app-53532-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ijob-app-53532.appspot.com',
    androidClientId: '530270654942-j5tf1lkquqf7itbr1bs1jshqi2nkhb8v.apps.googleusercontent.com',
    iosClientId: '530270654942-t5a4ndbf79f6j45g6hg3ik2cd0j34msa.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappUc',
  );
}
